[build]
target = "aarch64-unknown-none-softfloat"  # 64-bit bare metal, no FP/SIMD (not enabled at boot)

[target.aarch64-unknown-none-softfloat]
rustflags = ["-C", "target-cpu=cortex-a53", "-C", "link-arg=--script=./linker.ld"]
