//! Writes the linker script user programs are linked with, from `rustypi_abi::layout`, and
//! puts it on the linker's search path. Programs select it with `-C link-arg=-Trustypi-user.ld`.

use rustypi_abi::layout::{PAGE_SIZE, PROGRAM_END, USER_BASE};
use std::path::PathBuf;
use std::{env, fs};

fn main() {
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    // Every segment starts on a page boundary, which the kernel's loader requires.
    let script = format!(
        "/* Generated by rustypi-user's build.rs from rustypi_abi::layout. */
ENTRY(_start)

SECTIONS
{{
    . = {USER_BASE:#x};
    .text : {{ KEEP(*(.text._start)) *(.text .text.*) }}

    . = ALIGN({PAGE_SIZE:#x});
    .rodata : {{ *(.rodata .rodata.*) }}

    . = ALIGN({PAGE_SIZE:#x});
    .data : {{ *(.data .data.*) *(.got .got.*) }}
    .bss : {{ *(.bss .bss.*) *(COMMON) }}

    ASSERT(. <= {PROGRAM_END:#x}, \"program too big for the user window\")

    /DISCARD/ : {{ *(.comment) *(.ARM.exidx*) *(.eh_frame*) *(.note*) }}
}}
"
    );
    fs::write(out.join("rustypi-user.ld"), script).unwrap();
    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rerun-if-changed=build.rs");
}
